### ISSUE TITLE
long reload times 

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#3]
Since I am often modifying my hammer spoon config, I have to reload it quite often, which normally just needs milliseconds.
Wich EnhancedSpaces it takes minutes – everytime :/

beachball keeps spinning.

Here my Hammerspoon console log:

024-11-07 08:16:10: -- Lazy extension loading enabled
2024-11-07 08:16:10: -- Loading ~/.hammerspoon/init.lua
2024-11-07 08:16:10: -- Loading extension: alert
2024-11-07 08:16:10: -- Loading Spoon: HammerText
2024-11-07 08:16:10: -- Loading extension: logger
2024-11-07 08:16:10: HammerText is running
2024-11-07 08:16:10: -- Loading extension: eventtap
2024-11-07 08:16:10: -- Loading extension: hotkey
2024-11-07 08:16:10: 08:16:10     hotkey: Enabled hotkey F17
2024-11-07 08:16:10:              hotkey: Enabled hotkey F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌃F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌃⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⌃F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⌃⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌥F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌥⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌃⌥F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌃⌥⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⌥F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⌥⇧F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ⌘⌃⌥F18
2024-11-07 08:16:10:              hotkey: Enabled hotkey ✧F18
2024-11-07 08:16:10: 08:16:10 ** Warning:hs.keycode: key '\' not found in active keymap; using ANSI-standard US keyboard layout as fallback, returning '42'
2024-11-07 08:16:10: -- Loading extension: application
2024-11-07 08:16:10: -- Loading Spoon: EnhancedSpaces
2024-11-07 08:16:10: -- Loading extension: window
2024-11-07 08:16:10: -- Loading extension: screen
2024-11-07 08:16:10: -- Loading extensions: window.filter
2024-11-07 08:18:02: -- Loading extension: menubar
2024-11-07 08:19:53: -- Loading extension: spoons
2024-11-07 08:21:43: 08:21:43     hotkey: Enabled hotkey ⌥TAB
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌥⇧TAB
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌥ESCAPE
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⇧1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⇧2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⇧3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⇧0
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃A
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃S
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃Q
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃W
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃D
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃F
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌥1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌥2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌥3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⌥1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⌥2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌃⌥3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥4
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥5
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥6
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥7
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌥8
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃4
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃5
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃6
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃7
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃8
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃9
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃0
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃O
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⌃P
2024-11-07 08:21:43: -- Loading extension: inspect
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧1
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧2
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧3
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧4
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧5
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧6
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧7
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧8
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧9
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧0
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧O
2024-11-07 08:21:43:              hotkey: Enabled hotkey ⌘⇧P
2024-11-07 08:21:43: -- Done.

**Comment by franzbu** [comment]
So it is literally taking minutes to load? That is weird. It is just a couple of seconds here on an M3 Mac:

2024-11-07 14:26:45: -- Lazy extension loading enabled
2024-11-07 14:26:45: -- Loading ~/.hammerspoon/init.lua
2024-11-07 14:26:45: -- Loading extension: hotkey
2024-11-07 14:26:45: -- Loading extension: eventtap
2024-11-07 14:26:45: -- Loading extension: image
2024-11-07 14:26:45: -- Loading extension: screen
2024-11-07 14:26:45: -- Loading extension: canvas
2024-11-07 14:26:45: -- Loading extension: fnutils
2024-11-07 14:26:45: 14:26:45     hotkey: Enabled hotkey ⌘⌃⇧X
2024-11-07 14:26:45: -- Loading extension: chooser
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌃⇧D
2024-11-07 14:26:45: -- Loading Spoon: SpoonInstall
2024-11-07 14:26:45: -- Loading extension: logger
2024-11-07 14:26:45: -- Loading extension: pathwatcher
2024-11-07 14:26:45: -- Loading extension: alert
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧A
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧S
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧G
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧U
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧D
2024-11-07 14:26:45: -- Loading Spoon: EnhancedSpaces
2024-11-07 14:26:45: -- Loading extension: window
2024-11-07 14:26:45: -- Loading extensions: window.filter
2024-11-07 14:26:46: -- Loading extension: menubar
2024-11-07 14:26:46: -- Loading extension: geometry
2024-11-07 14:26:48: -- Loading extension: spoons
2024-11-07 14:26:49: 14:26:49     hotkey: Enabled hotkey ⌥TAB
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧TAB
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥ESCAPE
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧0
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧A
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧S
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧Q
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧W
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧D
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧F
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥5
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥6
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥7
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥8
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃5
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃6
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃7
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃8
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃9
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃0
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃O
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃P
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥R
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥M
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥I
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥O
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥L
2024-11-07 14:26:49: -- Loading extension: timer
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧X
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧V
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥X
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥U
2024-11-07 14:26:49: -- Loading Spoon: AClock
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥C
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥H
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥B
2024-11-07 14:26:49: -- Done.

**Comment by franzbu** [comment]
Here is the log:
2024-11-07 14:26:45: -- Lazy extension loading enabled
2024-11-07 14:26:45: -- Loading ~/.hammerspoon/init.lua
2024-11-07 14:26:45: -- Loading extension: hotkey
2024-11-07 14:26:45: -- Loading extension: eventtap
2024-11-07 14:26:45: -- Loading extension: image
2024-11-07 14:26:45: -- Loading extension: screen
2024-11-07 14:26:45: -- Loading extension: canvas
2024-11-07 14:26:45: -- Loading extension: fnutils
2024-11-07 14:26:45: 14:26:45     hotkey: Enabled hotkey ⌘⌃⇧X
2024-11-07 14:26:45: -- Loading extension: chooser
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌃⇧D
2024-11-07 14:26:45: -- Loading Spoon: SpoonInstall
2024-11-07 14:26:45: -- Loading extension: logger
2024-11-07 14:26:45: -- Loading extension: pathwatcher
2024-11-07 14:26:45: -- Loading extension: alert
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧A
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧S
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧G
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧U
2024-11-07 14:26:45:              hotkey: Enabled hotkey ⌘⌃⇧D
2024-11-07 14:26:45: -- Loading Spoon: EnhancedSpaces
2024-11-07 14:26:45: -- Loading extension: window
2024-11-07 14:26:45: -- Loading extensions: window.filter
2024-11-07 14:26:46: -- Loading extension: menubar
2024-11-07 14:26:46: -- Loading extension: geometry
2024-11-07 14:26:48: -- Loading extension: spoons
2024-11-07 14:26:49: 14:26:49     hotkey: Enabled hotkey ⌥TAB
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧TAB
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥ESCAPE
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌃⇧0
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧A
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧S
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧Q
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧W
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧D
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧F
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌥⇧T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥5
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥6
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥7
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥8
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃1
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃2
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃3
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃5
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃6
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃7
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃8
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃9
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃0
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃O
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃P
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥E
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥R
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥T
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥M
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥I
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥O
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥L
2024-11-07 14:26:49: -- Loading extension: timer
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧X
2024-11-07 14:26:49:              hotkey: Enabled hotkey ✧V
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌥X
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘4
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥U
2024-11-07 14:26:49: -- Loading Spoon: AClock
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥C
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥H
2024-11-07 14:26:49:              hotkey: Enabled hotkey ⌘⌃⌥B
2024-11-07 14:26:49: -- Done.

**Comment by franzbu** [comment]
Loading these 3 extensions seems to make the difference:

2024-11-07 08:16:10: -- Loading extensions: window.filter
2024-11-07 08:18:02: -- Loading extension: menubar
2024-11-07 08:19:53: -- Loading extension: spoons

What is your hardware configuration? Which version of Hammerspoon do you use?

Have you tried to disable other spoons (or code in your init.lua) to see whether there is some kind of interference?

**Comment by martinengelke** [comment]
I just created a clean init.lua with only your Spoon loading. 
– same result. 

I am running a MBPro 14" 2024 M3Pro on macOS 14.5,
HammerSpoon v1.0.0 (6864), which is managed via homebrew.

I will do a restart now first.

**Comment by franzbu** [comment]
The only obvious difference in our configurations is the version of macOS: 14.5 vs. 15.1. Please keep me posted.

**Comment by martinengelke** [comment]
After restart it works fast as aspected with just the EnhancedSpaces spoon loading. It just throws an alert:

<img width="1169" alt="Bildschirmfoto 2024-11-07 um 13 49 52" src="https://github.com/user-attachments/assets/28c6f3a3-a278-42a3-8733-a1ebf1bb4532">

**Comment by franzbu** [comment]
Oh, good! About the alert: if you're on v0.9.26, would you mind commenting out (or deleting) line 344

hs.alert.show(hs.inspect(modifierSnap3))

It will be corrected with the next version.

edit: with v0.9.27 this should be fixed along with other fixes.

**Comment by martinengelke** [comment]
By the way: you forgot to increase the version number in the about dialog.
